version: "3.2"

services:
  db:
    image: mariadb:10.3.8
    environment:
      - "MYSQL_ROOT_PASSWORD=db-root-password"
      - "MYSQL_USER=plancul"
      - "MYSQL_PASSWORD=db-password"
      - "MYSQL_DATABASE=plancul"
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - 3310:3306

  almanac:
    image: almanac

  app:
    image: payara/server-full:5.183
    entrypoint:
      - '/opt/payara/bin/asadmin'
      - 'start-domain'
      - '-v'
      - '--postbootcommandfile'
      - '/opt/payara/deployments/post-boot.sh'
      - 'domain1'
    environment:
      - 'mp.jwt.verify.publickey.location=https://localhost:8443/info/app/plancul/publicKey'
      - 'mp.jwt.verify.issuer=localhost:8443'
    volumes:
      - ./post-boot.sh:/opt/payara/deployments/post-boot.sh
      - ./secrets/authenticator.managementApi.secret:/opt/payara/secrets/com.charlyghislain.plancul.authenticator.managementApi.secret
      - ./auth-public-key.pem:/opt/payara/auth-public-key.pem
      - ./mariadb-java-client.jar:/opt/payara/glassfish/domains/domain1/lib/mariadb-java-client.jar
      - ./plancul-ear.ear:/opt/payara/deployments/plancul-ear.ear
      - ./keystore.jks:/opt/payara/glassfish/domains/domain1/config/keystore.jks
      - ./cacerts.jks:/opt/payara/glassfish/domains/domain1/config/cacerts.jks
    ports:
      - 8183:8181

volumes:
  db-data: {}
