version: "3.2"

services:
  db:
    image: mariadb:10.3.8
    environment:
      - "MYSQL_ROOT_PASSWORD=db-root-password"
      - "MYSQL_USER=plancul"
      - "MYSQL_PASSWORD=db-password"
      - "MYSQL_DATABASE=plancul"
    networks:
      default:
        aliases:
          - plancul-db
    volumes:
      - db-data:/var/lib/mysql
      - ./astronomy-db-init.sql:/docker-entrypoint-initdb.d/astronomy-db-init.sql
    ports:
      - 3310:3306


  app:
    image: payara/server-full:5.183
    entrypoint:
      - '/opt/payara/bin/asadmin'
      - 'start-domain'
      - '-v'
      - '--debug'
      - '--postbootcommandfile'
      - '/opt/payara/deployments/post-boot.sh'
      - 'domain1'
    networks:
      default: {}
      auth:
        aliases:
          - plancul
    environment:
      - 'mp_jwt_verify_issuer=localhost:8443'
      - 'com_charlyghislain_plancul_authenticator_managementApi_url=https://authenticator:8443/authenticator-web/management'
      - 'com_charlyghislain_plancul_almanac_api_url=http://almanac:2828'
    volumes:
      - ./post-boot.sh:/opt/payara/deployments/post-boot.sh
      - ./secrets/authenticator.managementApi.secret:/opt/payara/secrets/com.charlyghislain.plancul.authenticator.managementApi.secret
      - ./secrets/auth-public-key.pem:/opt/payara/secrets/mp.jwt.verify.publickey
      - ./mariadb-java-client.jar:/opt/payara/glassfish/domains/domain1/lib/mariadb-java-client.jar
      - ./plancul-ear.ear:/opt/payara/deployments/plancul-ear.ear
      - ./keystore.jks:/opt/payara/glassfish/domains/domain1/config/keystore.jks
      - ./cacerts.jks:/opt/payara/glassfish/domains/domain1/config/cacerts.jks
    ports:
      - 8444:8181
      - 9002:9009


#  front-en:
#    image: docker.valuya.be/plancul-front:3
#    environment:
#     - 'LANG=en'
#     - 'ARCHIVE_REF=rc.en.latest'
#     - 'OVERWRITE_TARGET_DIR=true'
#     - 'CONTEXT_PATH=/'
#     - 'PLANCUL_WS_URL=https://localhost:8444/ws'
#     - 'PLANCUL_AUTHENTICATOR_API_URL=https://localhost:0443/ws'
#     - 'PLANCUL_ASTRONOMY_API_URL=https://localhost:8444/astronomy-ws'
#     - 'PLANCUL_AUTHENTICATOR_APP_NAME=plancul'
#     - 'PLANCUL_PUBLIC_URL_BASE=https://localhost:8002'
#    volumes:
#      - ./secrets/nexus-basic-auth:/var/run/secrets/nexus-basic-auth
#    ports:
#      - 8002:80


  almanac:
    image: cghislai/almanac
    ports:
      - 8000:2828


volumes:
  db-data: {}

networks:
  default: {}
  auth:
    external:
      name: authenticator-stack_default

