package com.charlyghislain.plancul.api.domain.request.sort;

public enum WsCultureSortField {
    CROP_PLANT_NAME,
    CROP_PRODUCT_NAME,
    CROP_CULTIVAR,
    BED_NAME,
    SOWING_DATE,
    GERMINATION_DATE,
    FIRST_HARVEST_DATE,
    LAST_HARVEST_DATE,
    BED_OCCUPANCY_START_DATE,
    BED_OCCUPANCY_END_DATE,
    HTML_NOTES,
    NURSERING_DURATION,
    NURSERING_START_DATE,
    CULTURE_PREPARATION_DURATION,
    CULTURE_PREPARATION_START_DATE,
    CREATED,
    UPDATED;

}
